# Generated by Django 5.0.2 on 2024-02-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Изображение'),
        ),
    ]
